// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521220540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Proyectos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Proyecto Alpha",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Proyecto Alpha 2",
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Proyecto Beta 1",
                            WorkspaceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Proyecto Beta 2",
                            WorkspaceId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Editor"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Lector"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Password = "$2a$11$ydqvSD7yQ88lg6kCm..wUuGLp1pMqiY7RJqoyOYpQd6x4t0uWEUl."
                        },
                        new
                        {
                            Id = 4,
                            Email = "test1@ejemplo.com",
                            Password = "$2a$11$ydqvSD7yQ88lg6kCm..wUuGLp1pMqiY7RJqoyOYpQd6x4t0uWEUl."
                        });
                });

            modelBuilder.Entity("Domain.Entities.UsuarioWorkspace", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "WorkspaceId");

                    b.HasIndex("RolId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Usuario_Workspace", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            WorkspaceId = 1,
                            RolId = 1
                        },
                        new
                        {
                            UsuarioId = 1,
                            WorkspaceId = 2,
                            RolId = 3
                        },
                        new
                        {
                            UsuarioId = 4,
                            WorkspaceId = 1,
                            RolId = 2
                        },
                        new
                        {
                            UsuarioId = 4,
                            WorkspaceId = 2,
                            RolId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Alfa"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Beta"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Proyecto", b =>
                {
                    b.HasOne("Domain.Entities.Workspace", "Workspace")
                        .WithMany("Proyectos")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Entities.UsuarioWorkspace", b =>
                {
                    b.HasOne("Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioWorkspaces")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioWorkspaces")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Workspace", "Workspace")
                        .WithMany("UsuarioWorkspaces")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioWorkspaces");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioWorkspaces");
                });

            modelBuilder.Entity("Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Proyectos");

                    b.Navigation("UsuarioWorkspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
